services:

  foodfy:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${FOODFY_PORT-5000}:${FOODFY_PORT-5000}
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FOODFY_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}

  run_seed:
    build: 
      dockerfile: Dockerfile.seed
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT} 

  postgres:
    image: postgres
    ports: 
      - ${DB_PORT}:5432
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./foodfy.sql:/docker-entrypoint-initdb.d/foodfy.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s

  #pgadmin:
  #  image: dpage/pgadmin4
  #  ports:
  #    - ${PGADM_PORT}:80
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=${PGADM_EMAIL}
  #    - PGADMIN_DEFAULT_PASSWORD=${PGADM_PASSWORD}     

  