services:

  foodfy:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${FOODFY_PORT-5000}:${FOODFY_PORT-5000}
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FOODFY_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}

  email:
    build: .
    depends_on:
      rabbitmq: 
        condition: service_healthy
    command: [ "node", "src/email/email-service.js" ]

  run_seed:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: [ "node", "seed.js" ]

  postgres:
    image: postgres
    ports: 
      - ${DB_PORT}:5432
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./foodfy.sql:/docker-entrypoint-initdb.d/foodfy.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBIT_PORT-15672}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    
    

  #pgadmin:
  #  image: dpage/pgadmin4
  #  ports:
  #    - ${PGADM_PORT}:80
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=${PGADM_EMAIL}
  #    - PGADMIN_DEFAULT_PASSWORD=${PGADM_PASSWORD}     

  