services:

  front:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${FRONT_PORT-5000}:${FRONT_PORT-5000}
    working_dir: /opt/app/frontend
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FRONT_PORT=${FRONT_PORT}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - HOME_URL=${HOME_URL}
      - SESSIONS_PORT=${SESSIONS_PORT}
      - SESSIONS_URL=${SESSIONS_URL}
      - RECIPES_PORT=${RECIPES_PORT}
      - RECIPES_URL=${RECIPES_URL}
      - CHEFS_URL=${CHEFS_URL}
      - CHEFS_PORT=${CHEFS_PORT}

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${API_PORT-5001}:${API_PORT-5001}
    working_dir: /opt/app/api
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FRONT_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - HOME_URL=${HOME_URL}
      - API_PORT=${API_PORT}

  home:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${HOME_PORT-5002}:${HOME_PORT-5002}
    working_dir: /opt/app/home-service  
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FRONT_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - HOME_URL=${HOME_URL}
      - HOME_PORT=${HOME_PORT}

  sessions:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${SESSIONS_PORT-5003}:${SESSIONS_PORT-5003}
    working_dir: /opt/app/sessions-service  
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FRONT_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - HOME_URL=${HOME_URL}
      - HOME_PORT=${HOME_PORT}
      - SESSIONS_PORT=${SESSIONS_PORT}
      - SESSIONS_URL=${SESSIONS_URL}
      - RECIPES_PORT=${RECIPES_PORT}
      - RECIPES_URL=${RECIPES_URL}

  recipes:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${RECIPES_PORT-5004}:${RECIPES_PORT-5004}
    working_dir: /opt/app/recipes-service  
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FRONT_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - HOME_URL=${HOME_URL}
      - HOME_PORT=${HOME_PORT}
      - SESSIONS_PORT=${SESSIONS_PORT}
      - SESSIONS_URL=${SESSIONS_URL}
      - RECIPES_PORT=${RECIPES_PORT}
      - RECIPES_URL=${RECIPES_URL}

  chefs:
    build: .
    depends_on:
      postgres:
        condition: service_healthy 
      run_seed:
        condition: service_completed_successfully
    ports:
      - ${CHEFS_PORT-5005}:${CHEFS_PORT-5005}
    working_dir: /opt/app/chefs-service  
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - FRONT_PORT=${FOODFY_PORT}
      - DB_PORT=${DB_PORT}
      - API_URL=${API_URL}
      - HOME_URL=${HOME_URL}
      - HOME_PORT=${HOME_PORT}
      - SESSIONS_PORT=${SESSIONS_PORT}
      - SESSIONS_URL=${SESSIONS_URL}
      - CHEFS_PORT=${CHEFS_PORT}
      - CHEFS_URL=${CHEFS_URL}

  run_seed:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: [ "node", "seed.js" ]

  postgres:
    image: postgres
    ports: 
      - ${DB_PORT}:5432
    environment: 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./foodfy.sql:/docker-entrypoint-initdb.d/foodfy.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 30s    
    

  #pgadmin:
  #  image: dpage/pgadmin4
  #  ports:
  #    - ${PGADM_PORT}:80
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=${PGADM_EMAIL}
  #    - PGADMIN_DEFAULT_PASSWORD=${PGADM_PASSWORD}     

  